process_ddl_interval: "60s"    # 每 1 分鐘執行一次DDL批次處理
process_dml_interval: "600s"   # 每 10 分鐘執行一次DML批次處理
process_timeout: "30s"    # 單次批次處理timeout 為30秒
dml_log_generate_interval: "3m"

prometheus:
  metrics_port: 2112 # metrics 暴露 port

mq:
  # RabbitMQ 連線 URL，帳號密碼 SCIMIS:27128299，注意區分大小寫
  amqp_url:     "amqp://SCIMIS:27128299@218.32.20.208:5672/"
  # TLS 憑證檔案路徑
  cert_file:    "certs/PmsApClient.crt"
  key_file:     "certs/PmsApClient.key"
  ca_cert_file: "certs/ca.crt"
  # 連線逾時 (字串)，程式裡用 time.ParseDuration 解析
  timeout:      "30s"
  confirm_timeout: "10s"
  dead_letter_exchange: "bi_dlx_exchange"
  dead_letter_queue: "ddl_dml_dead_queue"
  dead_letter_routing_key: "dead_ddldml"
  primary_exchange: "bi_main_exchange"
  primary_queue: "ddl_dml_main_queue"

db:
  host:      "SPT-176.sprinta.com"
  # instance:  "PH1"
  # SQL Server 連接埠 (如有需要)
  # port:         1433
  # 登入帳號、密碼
  user:         "SCIMIS"
  password:     "27128299"
  # Initial Catalog
  name:         "POWERBIReportData"
  # 加密方式 (disable 或 require)
  encrypt:      "disable"
  # 連線逾時 (字串)，程式裡用 time.ParseDuration 解析
  timeout:      "60s"
  query_timeout: "30s"
