process_ddl_interval: "15s"    # 每 5 分鐘執行一次DDL批次處理
process_dml_interval: "1h"    # 每 1 小時小時執行一次DML批次處理
process_timeout: "1m"    # 單次批次處理timeout 為30秒
consumer_count: 10 # consumer數量

prometheus:
  metrics_port: 2113 # metrics 暴露 port

mq:
  # RabbitMQ 連線 URL（含使用 TLS 時的 amqps）
  amqp_url:     "amqps://root:admin1234@localhost:5671/"
  # TLS 憑證檔案路徑
  cert_file:    "certs/PmsApClient.crt"
  key_file:     "certs/PmsApClient.key"
  ca_cert_file: "certs/ca.crt"
  # 連線逾時 (字串)，程式裡用 time.ParseDuration 解析
  timeout:      "5s"
  dead_letter_exchange: "ddldml_dlx_exchange_test"
  dead_letter_queue: "ddl_dml_dead_queue_test"
  dead_letter_routing_key: "dead_ddldml_test"
  primary_exchange: "bi_direct_test"
  primaryqueue: "ddl_dml_main_queue_test"

db:
  host:      "PMSDB"
  instance:  "POWERBI"
  # SQL Server 連接埠 (如有需要)
  # port:         1433
  # 登入帳號、密碼
  user:         "SCIMIS"
  password:     "27128299"
  # Initial Catalog
  name:         "PBIReportData_Test"
  # 加密方式 (disable 或 require)
  encrypt:      "disable"
  # 連線逾時 (字串)，程式裡用 time.ParseDuration 解析
  timeout:      "5s"
